eval "$(/opt/homebrew/bin/brew shellenv)"
source "$HOME/dotfiles/shell/prompt.sh"

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

. "$HOME/.cargo/env"

. "$HOME/.local/bin/env"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/ty/.lmstudio/bin"
# End of LM Studio CLI section
