if [[ -f ~/.bashrc ]]; then
    source ~/.bashrc
fi
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

# Required for pylsp to work properly,
# when setting `language en_US` in init.vim.
export LC_CTYPE=ja_JP.UTF-8

# Added by Toolbox App
export PATH="$PATH:/Users/ty/Library/Application Support/JetBrains/Toolbox/scripts"

export PATH="$PATH:$HOME/go/bin"
[ -f "$HOME/.local/bin/env" ] && . "$HOME/.local/bin/env"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/ty/.lmstudio/bin"
# End of LM Studio CLI section
